# Generated by Django 6.0.3 on 2026-04-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_order_status_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_total',
            field=models.IntegerField(default=0),
        ),
    ]
