# Generated by Django 6.0.2 on 2026-04-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_original_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cus_id', models.CharField(db_collation='Thai_CI_AS', db_column='Cus_ID', max_length=5, primary_key=True, serialize=False)),
                ('cus_name', models.CharField(db_collation='Thai_CI_AS', db_column='Cus_name', max_length=20)),
                ('room_id', models.CharField(db_collation='Thai_CI_AS', db_column='Room_ID', max_length=5)),
                ('telephone', models.CharField(db_collation='Thai_CI_AS', db_column='Telephone', max_length=20)),
                ('member_type', models.CharField(blank=True, db_collation='Thai_CI_AS', db_column='Member_Type', max_length=10, null=True)),
                ('regist_date', models.DateField(db_column='Regist_Date')),
                ('total_points', models.IntegerField(db_column='Total_Points')),
            ],
            options={
                'db_table': 'dbo].[Customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.CharField(db_collation='Thai_CI_AS', db_column='Emp_ID', max_length=5, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(db_collation='Thai_CI_AS', db_column='Emp_name', max_length=50)),
                ('position', models.CharField(db_collation='Thai_CI_AS', db_column='Position', max_length=50)),
                ('telephone', models.CharField(db_collation='Thai_CI_AS', db_column='Telephone', max_length=20)),
            ],
            options={
                'db_table': 'Employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_detail_id', models.AutoField(db_column='Order_Detail_ID', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(db_column='Unit_Price', decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(db_column='Sub_Total', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Order_Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(db_collation='Thai_CI_AS', db_column='Order_ID', max_length=5, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(db_column='Order_date')),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('is_express', models.CharField(db_collation='Thai_CI_AS', db_column='Is_Express', max_length=10)),
                ('total_amount', models.DecimalField(db_column='Total_Amount', decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(blank=True, db_column='Discount_Amount', decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(db_collation='Thai_CI_AS', db_column='Order_Status', max_length=20)),
                ('actual_pickup_date', models.DateTimeField(blank=True, db_column='Actual_Pickup_Date', null=True)),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('pay_id', models.AutoField(db_column='Pay_ID', primary_key=True, serialize=False)),
                ('pay_date', models.DateTimeField(db_column='Pay_Date')),
                ('pay_method', models.CharField(db_collation='Thai_CI_AS', db_column='Pay_Method', max_length=20)),
                ('pay_amount', models.DecimalField(db_column='Pay_Amount', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RewardRules',
            fields=[
                ('reward_id', models.IntegerField(db_column='Reward_ID', primary_key=True, serialize=False)),
                ('reward_name', models.CharField(db_collation='Thai_CI_AS', db_column='Reward_Name', max_length=50)),
                ('points_required', models.IntegerField(db_column='Points_Required')),
                ('discount_value', models.DecimalField(db_column='Discount_Value', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Reward_Rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.CharField(db_collation='Thai_CI_AS', db_column='Service_ID', max_length=5, primary_key=True, serialize=False)),
                ('category', models.CharField(db_collation='Thai_CI_AS', db_column='Category', max_length=50)),
                ('item_name', models.CharField(db_collation='Thai_CI_AS', db_column='Item_Name', max_length=50)),
                ('unit_type', models.CharField(db_collation='Thai_CI_AS', db_column='Unit_type', max_length=20)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('express_price', models.DecimalField(db_column='Express_Price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Thai_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VDailyrevenue',
            fields=[
                ('order_date', models.DateField(db_column='Order_Date', primary_key=True, serialize=False)),
                ('total_daily_revenue', models.DecimalField(db_column='Total_Daily_Revenue', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'v_DailyRevenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VOrderstatus',
            fields=[
                ('order_id', models.IntegerField(db_column='Order_ID', primary_key=True, serialize=False)),
                ('cus_name', models.CharField(db_column='Cus_Name', max_length=100)),
                ('order_status', models.CharField(db_column='Order_Status', max_length=50)),
            ],
            options={
                'db_table': 'v_OrderStatus',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
